name: postos
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  intl: ^0.19.0
  dio: ^5.7.0
  collection: ^1.18.0
  brasil_fields: ^1.15.0
  super_sliver_list: ^0.4.1
  badges: ^3.1.2
  device_info_plus: ^11.1.0
  web: ^1.1.0   # <-- PRECISA DISSO AGORA
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cestasnatal.mp4
    - web/postos.json
